plugins:
  - { url: 'git@github.com:chr4/nginx.vim.git', path: 'nginx.vim' }
  - { url: 'git@github.com:jiangmiao/auto-pairs.git', path: 'auto-pairs.git' }
  - { url: 'git@github.com:itchyny/lightline.vim.git', path: 'lightline.vim' }
  - { url: 'git@github.com:godlygeek/tabular.git', path: 'tabular.git' }
  - { url: 'git@github.com:michaeljsmith/vim-indent-object.git', path: 'vim-indent-object.git' }
  - { url: 'git@github.com:plasticboy/vim-markdown.git', path: 'vim-markdown.git' }
  - { url: 'git@github.com:terryma/vim-multiple-cursors.git', path: 'vim-multiple-cursors.git' }

folders:
  - 'temp_dirs/undodir'
  - 'indent'
  - 'syntax'
  - 'ftplugin'
  - 'pack/my-plugins/start'
  - 'pack/my-plugins/opt'
  - 'autoload'

files:
  - { file: 'groovy.vim', path: '.vim/indent' }
  - { file: 'groovy.vim', path: '.vim/syntax' }
  - { file: 'dsl.vim', path: '.vim/syntax' }
  - { file: 'yaml.vim', path: '.vim/ftplugin' }
  - { file: '.vimrc', path: './' }
